version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/blog-api

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 1200
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server
      timeout: 1200
      runas: ec2-user

